#!/usr/bin/env bash
# CLAUDE GENERATED
#
# Stand up a local Hermes ACP server and run the Oscillitron gated
# integration test + demo against it. Idempotent: re-running won't
# re-clone if the checkout already exists.
#
# Usage:
#   ./scripts/setup-hermes-local.sh            # full setup + integration test + demo
#   ./scripts/setup-hermes-local.sh test       # just the integration test (assumes setup is done)
#   ./scripts/setup-hermes-local.sh demo       # just the demo (assumes setup is done)
#
# Env overrides:
#   HERMES_DIR     where to clone hermes-agent  (default: $HOME/hermes-agent)
#   HERMES_WRAPPER path to the shell wrapper    (default: $HOME/bin/hermes-acp)

set -euo pipefail

HERMES_DIR="${HERMES_DIR:-$HOME/hermes-agent}"
HERMES_WRAPPER="${HERMES_WRAPPER:-$HOME/bin/hermes-acp}"
REPO_URL="https://github.com/NousResearch/hermes-agent"

# Resolve oscillitron repo root from this script's location.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
OSCI_DIR="$(cd -- "$SCRIPT_DIR/.." &> /dev/null && pwd)"

mode="${1:-all}"

log() { printf '\033[1;36m[setup-hermes]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[setup-hermes]\033[0m %s\n' "$*" >&2; exit 1; }

setup_hermes() {
  if [ ! -d "$HERMES_DIR/.git" ]; then
    log "cloning $REPO_URL -> $HERMES_DIR"
    git clone "$REPO_URL" "$HERMES_DIR"
  else
    log "hermes checkout already present at $HERMES_DIR (skipping clone)"
  fi

  # Detect if hermes is already installed by looking for the venv binary
  # that setup-hermes.sh produces. If present, skip the install — re-running
  # it is slow and triggers interactive prompts.
  if [ -x "$HERMES_DIR/venv/bin/hermes" ]; then
    log "hermes already installed at $HERMES_DIR/venv/bin/hermes (skipping setup-hermes.sh)"
    return 0
  fi

  log "running hermes setup script (./setup-hermes.sh, non-interactive)"
  pushd "$HERMES_DIR" > /dev/null
  if [ -x ./setup-hermes.sh ]; then
    # setup-hermes.sh has interactive `read -p` prompts for the ripgrep
    # install and the setup wizard. Feed defaults via stdin so it
    # finishes non-interactively under `set -e`.
    # n = skip ripgrep, n = skip wizard.
    printf 'n\nn\n' | ./setup-hermes.sh || die "setup-hermes.sh failed (rerun manually in a TTY to diagnose)"
  else
    log "no setup-hermes.sh found — falling back to: uv sync (if available) or pip install"
    if command -v uv >/dev/null 2>&1; then
      uv sync
    else
      python3 -m pip install -e .
    fi
  fi
  popd > /dev/null

  [ -x "$HERMES_DIR/venv/bin/hermes" ] || die "hermes binary not found at $HERMES_DIR/venv/bin/hermes after setup"
}

write_wrapper() {
  local wrapper_dir
  wrapper_dir="$(dirname "$HERMES_WRAPPER")"
  mkdir -p "$wrapper_dir"
  log "writing wrapper -> $HERMES_WRAPPER"
  # The Hermes ACP server is exposed via the `acp` subcommand of the
  # hermes CLI (which routes to acp_adapter.entry:main). Invoke the venv
  # binary directly so we don't depend on PATH ordering.
  #
  # Env-var overrides: Hermes' auxiliary-client router still tries
  # OpenRouter as a fallback even when ~/.hermes/config.yaml says
  # provider: ollama. Force the OpenAI-compatible env vars + the
  # explicit provider flag so every code path resolves to local Ollama.
  cat > "$HERMES_WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by oscillitron/scripts/setup-hermes-local.sh
export HERMES_INFERENCE_PROVIDER=custom
export OPENAI_BASE_URL=http://127.0.0.1:11434/v1
export OPENAI_API_KEY=ollama
export OLLAMA_BASE_URL=http://127.0.0.1:11434
exec "$HERMES_DIR/venv/bin/hermes" acp "\$@"
EOF
  chmod +x "$HERMES_WRAPPER"
}

verify_wrapper() {
  [ -x "$HERMES_WRAPPER" ] || die "wrapper $HERMES_WRAPPER not found or not executable. Run without args first."
}

run_test() {
  verify_wrapper
  log "running gated integration test"
  cd "$OSCI_DIR"
  OSCILLITRON_HERMES_BIN="$HERMES_WRAPPER" \
  OSCILLITRON_HERMES_CWD="$OSCI_DIR" \
    go test -count=1 -v ./internal/test/hermes/...
}

run_demo() {
  verify_wrapper
  log "running demo (single-node code topology, real Hermes)"
  cd "$OSCI_DIR"
  OSCILLITRON_HERMES_BIN="$HERMES_WRAPPER" \
  OSCILLITRON_HERMES_CWD="$OSCI_DIR" \
    go run ./cmd/oscillitron
}

case "$mode" in
  all)
    setup_hermes
    write_wrapper
    run_test
    run_demo
    ;;
  setup)
    setup_hermes
    write_wrapper
    ;;
  test)
    run_test
    ;;
  demo)
    run_demo
    ;;
  *)
    die "unknown mode: $mode (expected one of: all, setup, test, demo)"
    ;;
esac

log "done."
